model: default
model_type: "sat"

pretrain: True
# pretrain_path: './weights/sat_hmr/sat_644.pth'
# pretrain_path: '/home/cglee/SAT-HMR/outputs/ckpts/train_all/epoch_13_step_31569/pytorch_model.bin'
# pretrain_path: '/home/cglee/SAT-HMR/outputs/ckpts/train_all_sat_pr_sam2/epoch_13_step_20705/pytorch_model.bin'
pretrain_path: '/home/cglee/SAT-HMR/outputs/ckpts/train_all_sat_pr_sam2_test/epoch_1_step_23685/pytorch_model.bin'

input_dir: './data/datasets/Posetrack/PoseTrack2018/images/val'
output_dir: './tracking_results/baseline_trn13_pr'
conf_thresh: [0.15]
infer_batch_size: 1
infer_num_workers: 2
distributed_infer: True

iou_match_thresh: 0.1
iou_new_thresh: 0.5
max_age: 10

total_gpus: 4