seed: 42
model: default

pretrain: True
pretrain_path: 'weights/sat_hmr/sat_644.pth'
resume: True # Resume from the latest ckpt

model_type: "sat"
num_epochs: 60
save_and_eval_epoch: 1
least_eval_epoch: 1
sat_gt_epoch: 1
# lr
lr: 4.0e-5
lr_encoder_names: ["encoder"]
lr_encoder: 2.0e-6
lr_propmt: 4.0e-5
# optimizer AdamW
optimizer: 'adamw'
weight_decay: 0.0001
num_warmup_steps: 0
lr_scheduler: 'cosine'
aux_loss: True

losses: ['confs','poses','betas','boxes','j3ds','j2ds','depths','scale_map']
weight_dict: {'confs':4.,'poses':5.,'betas':3.,'boxes':2., 'giou':2., 'j3ds':8.,'j2ds':40.,'depths':0.5, 'map_confs': 4., 'map_scales': 4.}
# weight_dict: {'confs':4.,'poses':5.,'betas':3.,'boxes':2., 'giou':2., 'j3ds':8.,'j2ds':40.,'depths':0.5, 'map_confs': 4., 'map_scales': 4.,
#               'confs_pr':4.,'poses_pr':5.,'betas_pr':3.,'boxes_pr':2., 'giou_pr':2., 'j3ds_pr':8.,'j2ds_pr':40.,'depths_pr':0.5, 
#               'map_confs_pr': 4., 'map_scales_pr': 4.}
detach_j3ds: False

# matcher
set_cost_conf: 1
set_cost_bbox: 1
set_cost_giou: 1
set_cost_kpts: 20

# train aug
aug_cfg:
  rot_range: [-15, 15]
  scale_range: [0.8, 1.8]
  flip_ratio: 0.5

train_datasets_used: ['3dpw']      # ['agora','bedlam','bedlam']
train_datasets_split: ['train']  # ['train','train_6fps','validation_6fps']
train_batch_size: 1
train_num_workers: 1

# eval_datasets_used: ['agora','bedlam']
# eval_datasets_split: ['validation','validation_6fps']
eval_datasets_used: ['3dpw']
eval_datasets_split: ['test']
eval_vis_num: 20
conf_thresh: [0.3]
eval_batch_size: 12
eval_num_workers: 8
distributed_eval: True